# Generated by Django 5.2.5 on 2026-06-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='landlord_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
