# Generated by Django 5.2.5 on 2026-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_account',
            field=models.BooleanField(default=True),
        ),
    ]
