# Generated by Django 5.2.5 on 2026-04-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('bedsitter', 'Bedsitter'), ('1br', '1 Bedroom'), ('2br', '2 Bedroom'), ('3br', '3 Bedroom')], default='bedsitter', max_length=20),
            preserve_default=False,
        ),
    ]
