# Generated by Django 5.2.5 on 2026-05-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-id']},
        ),
    ]
